name: Build PR

on:
  pull_request:
    branches: [site]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Prettify and Build

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Install Packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prettify
        uses: creyD/prettier_action@v3.1
        with:
          dry: true
          prettier_options: '--write {.,src/}**/*.{js,mdx}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
